### ISSUE TITLE
Trouble with a Yubikey OATH value

### ISSUE THREAD

**Issue by alanthing** [scalefactory/aws-assume-role#30]
I'm having some difficulty understanding why this isn't working. It might be with the smartcard gem, but I don't know how to debug to troubleshoot.

I have two Yubikeys: a 4C Nano and a Neo. I have the same virtual MFA credentials on both and they are named the same.

4C:
<img width="364" alt="y4c" src="https://user-images.githubusercontent.com/715868/35680273-e2c1cad2-0727-11e8-8879-7872d2788dbb.png">

```
$ ykman oath list | grep "Amazon Web Services"
Amazon Web Services:xxxx@main
```

Neo:
<img width="365" alt="yn" src="https://user-images.githubusercontent.com/715868/35680354-15f1f760-0728-11e8-9506-d210f46013eb.png">

```
$ ykman oath list | grep "Amazon Web Services"
Amazon Web Services:xxxx@main
```

Relevant portion from my `$HOME/.aws/config`:

```
[default]
output = json
region = us-east-1
s3 =
  signature_version = s3v4

[profile main-ro]
region = us-east-1
duration_seconds = 3600

[profile main]
role_arn = arn:aws:iam::123456789012:role/AdministratorsMFA
mfa_serial = automatic
source_profile = main-ro
role_session_name = xxxx
duration_seconds = 3600
yubikey_oath_name = Amazon Web Services:xxxx@main
```

When I use aws-assume-role with the 4C Nano, I get this:

```
$ aws-assume-role run -p main -- aws ec2 describe-regions --query 'sort_by(Regions, &RegionName)[].{R:RegionName}' --output text
Profile main not found in shared configuration.
error: key not found: "Amazon Web Services:xxxx@main"
```

If I remove the 4C Nano and insert the Neo, it works:

```
$ aws-assume-role run -p main -- aws ec2 describe-regions --query 'sort_by(Regions, &RegionName)[].{R:RegionName}' --output text
ap-northeast-1
...
```

What's very strange about this is that I have another profile save, that uses a completely different AWS account with no connection between them, and it works fine with the 4C Nano:

```
$ aws-assume-role run -p testing -- aws ec2 describe-regions --query 'sort_by(Regions, &RegionName)[].{R:RegionName}' --output text
ap-northeast-1
...
```

I can use both Yubkeys for GPG and other things. It's only this one particular OATH credential named `Amazon Web Services:xxxx@main` and only on one of the two smartcards. 

Is there something I can edit to show debug output?

**Comment by randomvariable** [comment]
There seems to be a problem with the upstream [YubiOATH](https://github.com/jamesottaway/yubioath/tree/master/lib/yubioath) gem or even the smartcard interface, as even on my key it doesn't show all of the entries. I thought it was order dependent, but from the look of your screenshot, this isn't true either.

If you want to see what Ruby can actually get at, try this in `irb` or `pry`:

``` ruby
require "smartcard"
require "yubioath"

context = Smartcard::PCSC::Context.new
raise "Yubikey not found" unless context.readers.length == 1
reader_name = context.readers.first
card = Smartcard::PCSC::Card.new(context, reader_name, :shared)
YubiOATH.new(card).calculate_all(timestamp: Time.now)
```
and see what's available in the array. On my key, the array length is half of what I actually have on the key.

**Comment by alanthing** [comment]
@randomvariable thank you for the quick reply. It looks like your assumption is correct as it only shows 2 of the 4 tokens on the 4C (I edited this output a little):

```
$ /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/irb
irb(main):001:0> require "smartcard"
=> true
irb(main):002:0> require "yubioath"
=> true
irb(main):003:0> context = Smartcard::PCSC::Context.new
=> #<Smartcard::PCSC::Context:0x007f1234567890 @_handle=1>
irb(main):004:0> raise "Yubikey not found" unless context.readers.length == 1
=> nil
irb(main):005:0> reader_name = context.readers.first
=> "Yubico Yubikey 4 U2F+CCID"
irb(main):006:0> card = Smartcard::PCSC::Card.new(context, reader_name, :shared)
=> #<Smartcard::PCSC::Card:0x007f1234567890 @context=#<Smartcard::PCSC::Context:0x007f1234567890 @_handle=1>, @sharing_mode=:shared, @_handle=1, @protocol=:t1, @send_pci=#<FFI::Library::Symbol name=g_rgSCardT1Pci address=0x007f1234567890>>
irb(main):007:0> YubiOATH.new(card).calculate_all(timestamp: Time.now)
=> {"Amazon Web Services:xxxx@testing"=>"999999", "gitlab.com:example@me.com"=>"999999"}
irb(main):008:0> quit

$ /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/irb
irb(main):001:0> require "smartcard"
=> true
irb(main):002:0> require "yubioath"
=> true
irb(main):003:0> context = Smartcard::PCSC::Context.new
=> #<Smartcard::PCSC::Context:0x007f1234567890 @_handle=1>
irb(main):004:0> raise "Yubikey not found" unless context.readers.length == 1
=> nil
irb(main):005:0> reader_name = context.readers.first
=> "Yubico Yubikey NEO U2F+CCID"
irb(main):006:0> card = Smartcard::PCSC::Card.new(context, reader_name, :shared)
=> #<Smartcard::PCSC::Card:0x007f1234567890 @context=#<Smartcard::PCSC::Context:0x007f1234567890 @_handle=1>, @sharing_mode=:shared, @_handle=1, @protocol=:t1, @send_pci=#<FFI::Library::Symbol name=g_rgSCardT1Pci address=0x007f1234567890>>
irb(main):007:0> YubiOATH.new(card).calculate_all(timestamp: Time.now)
=> {"Amazon Web Services:xxxx@testing"=>"999999", "gitlab.com:example@me.com"=>"999999", "GitHub:alanthing"=>"999999", "Amazon Web Services:xxxx@main"=>"999999"}
```

Something strange about this is that I have touch enabled on the GitLab and GitHub tokens on the 4C. I was not expecting it to show anything at all for the GitLab token on the first set of output. I wonder if there's a bug with the yubioath gem that doesn't know how to handle the touch property?

**Comment by alanthing** [comment]
Oddly, running `YubiOATH.new(card).list.keys` shows all entries.

**Comment by alanthing** [comment]
It returns a result when queried individually, but not with `calculate_all`:

```
irb(main):010:0> yubioath.calculate(name: "Amazon Web Services:xxxx@main", timestamp: Time.now)
=> "901109"
```

**Comment by alanthing** [comment]
I wish I knew Ruby better so I could do this myself, but looking at https://github.com/scalefactory/aws-assume-role/blob/51d63a9b11d294c276f3fb432cac2d5cfde0d019/lib/aws_assume_role/credentials/providers/mfa_session_credentials.rb#L70-L71

```ruby
def retrieve_yubikey_token
    raise t("options.mfa_token.smartcard_not_supported") unless SMARTCARD_SUPPORT
    context = Smartcard::PCSC::Context.new
    raise "Yubikey not found" unless context.readers.length == 1
    reader_name = context.readers.first
    card = Smartcard::PCSC::Card.new(context, reader_name, :shared)
    codes = YubiOATH.new(card).calculate_all(timestamp: Time.now)
    codes.fetch(BinData::String.new(@yubikey_oath_name))
end
```

Instead of using `calculate_all` if then looking up the code from the returned dict, could we `YubiOATH.new(card).calculate(@yubikey_oath_name, timestamp: Time.now)`

**Comment by randomvariable** [comment]
Seems reasonable. Happy for you to PR that.

**Comment by alanthing** [comment]
Sure thing -- quick question to help with that, how can I clear the "cache" that I get when I make a successful call? Seems like I normally have to wait an hour between MFA queries. With the aws-cli natively I would just nuke `~/.aws/cli/cache`

**Comment by randomvariable** [comment]
At the moment, it's a matter of deleting the individual entry from the OS X Keychain / GNOME Seahorse. I'll open a separate issue to add that as a CLI option.

**Comment by alanthing** [comment]
Many thanks for your help @randomvariable !
