### ISSUE TITLE
Compatibility with Glib 2.56+

### ISSUE THREAD

**Issue by randomvariable** [scalefactory/aws-assume-role#34]
Fedora 28 comes with Gnome 3.28, which includes Glib 2.56 drops IConv from being introspectable.

[gir_ffi gem has been updated](https://github.com/mvz/gir_ffi/blob/master/Changelog.md#0120--2018-03-024), but this isn't reflected in the keyring gem that aws-assume-role uses. These upstream dependencies also require Ruby 2.3 as a minimum.

This results in aws-assume-role being unusable on Fedora 28 at least. This may also affect newer versions of other Linux distributions.

**Comment by mbevc1** [comment]
https://github.com/mvz/gir_ffi/issues/94
or we can vendor from this version?

**Comment by mbevc1** [comment]
Upstream has restored Ruby 2.1 support: https://github.com/mvz/gir_ffi/pull/95
